# Generated by Django 4.2.11 on 2025-11-03 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productcategory',
            options={'ordering': ('name',), 'verbose_name': 'Categoria de producto', 'verbose_name_plural': 'Categorias de producto'},
        ),
        migrations.AddField(
            model_name='product',
            name='price_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Precio en dinero cuando price_type es 'money'.", max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='price_type',
            field=models.CharField(choices=[('points', 'Puntos'), ('money', 'Dinero')], default='points', max_length=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='points_cost',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
